### ISSUE TITLE
Repeated Question 

### ISSUE THREAD

**Issue by Abiji-2020** [Lets-code-with-us/DSA-Cracker#465]
In Blind code 75 there is one question which is repeated in two times i.e Question Number 44 and 50 both of them are `Merge K Sorted List` 

<img src ="https://github.com/Lets-code-with-us/DSA-Cracker/assets/145255212/d954ef0a-a3b2-4fd9-9223-e46d742bbf01">

Please review it

**Comment by dhruvabhat24** [comment]
Thanks for raising it. I will update it with a new question. But for you the same will be considered as you have solved it already.
